export default interface NYTarticle {
    abstract:string,
    byline:string,
    created_date:string,
    des_facet:string[],
    first_pusblished_date:string,
    geo_facet:string[],
    item_type: string,
    kicker: string,
    material_type_facet: string,
    multimedia: {
        caption:string,
        copyright: string,
        format: string,
        height: number,
        subtype: string,
        type: string,
        url: string,
        width: number,
    }[],
    published_date: string,
    section: string,
    slug_name: string,
    source: string,
    subheadline: string,
    subsection: string,
    title: string,
    updated_date: string,
    uri: string,
    url: string,
}